/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MeterId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Meter = IDL.Record({
  'id' : MeterId,
  'displayName' : IDL.Text,
  'owner' : UserId,
  'meterNumber' : IDL.Text,
  'createdAt' : Timestamp,
  'disco' : IDL.Text,
});
export const TransactionId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'token' : IDL.Opt(IDL.Text),
  'paymentMethod' : IDL.Text,
  'owner' : UserId,
  'meterNumber' : IDL.Text,
  'createdAt' : Timestamp,
  'creditAmount' : IDL.Nat,
  'disco' : IDL.Text,
});
export const AdminStats = IDL.Record({
  'totalCount' : IDL.Nat,
  'recentTransactions' : IDL.Vec(Transaction),
  'totalRevenue' : IDL.Nat,
});
export const TokenResult = IDL.Record({
  'token' : IDL.Text,
  'units' : IDL.Float64,
  'transactionId' : TransactionId,
});
export const ValidatedMeter = IDL.Record({
  'customerName' : IDL.Text,
  'meterNumber' : IDL.Text,
  'disco' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMeter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Meter], []),
  'completeOrder' : IDL.Func(
      [TransactionId, IDL.Text, IDL.Float64],
      [IDL.Opt(Transaction)],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Transaction],
      [],
    ),
  'deleteMeter' : IDL.Func([MeterId], [IDL.Bool], []),
  'failOrder' : IDL.Func([TransactionId], [IDL.Opt(Transaction)], []),
  'getAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getAdminStats' : IDL.Func([], [AdminStats], []),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], []),
  'getMeter' : IDL.Func([MeterId], [IDL.Opt(Meter)], ['query']),
  'getMeters' : IDL.Func([], [IDL.Vec(Meter)], ['query']),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getTransaction' : IDL.Func(
      [TransactionId],
      [IDL.Opt(Transaction)],
      ['query'],
    ),
  'purchaseToken' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : TokenResult, 'err' : IDL.Text })],
      [],
    ),
  'setAdmin' : IDL.Func([IDL.Principal], [], []),
  'validateMeter' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ValidatedMeter, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MeterId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Meter = IDL.Record({
    'id' : MeterId,
    'displayName' : IDL.Text,
    'owner' : UserId,
    'meterNumber' : IDL.Text,
    'createdAt' : Timestamp,
    'disco' : IDL.Text,
  });
  const TransactionId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'token' : IDL.Opt(IDL.Text),
    'paymentMethod' : IDL.Text,
    'owner' : UserId,
    'meterNumber' : IDL.Text,
    'createdAt' : Timestamp,
    'creditAmount' : IDL.Nat,
    'disco' : IDL.Text,
  });
  const AdminStats = IDL.Record({
    'totalCount' : IDL.Nat,
    'recentTransactions' : IDL.Vec(Transaction),
    'totalRevenue' : IDL.Nat,
  });
  const TokenResult = IDL.Record({
    'token' : IDL.Text,
    'units' : IDL.Float64,
    'transactionId' : TransactionId,
  });
  const ValidatedMeter = IDL.Record({
    'customerName' : IDL.Text,
    'meterNumber' : IDL.Text,
    'disco' : IDL.Text,
  });
  
  return IDL.Service({
    'addMeter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Meter], []),
    'completeOrder' : IDL.Func(
        [TransactionId, IDL.Text, IDL.Float64],
        [IDL.Opt(Transaction)],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Transaction],
        [],
      ),
    'deleteMeter' : IDL.Func([MeterId], [IDL.Bool], []),
    'failOrder' : IDL.Func([TransactionId], [IDL.Opt(Transaction)], []),
    'getAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getAdminStats' : IDL.Func([], [AdminStats], []),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], []),
    'getMeter' : IDL.Func([MeterId], [IDL.Opt(Meter)], ['query']),
    'getMeters' : IDL.Func([], [IDL.Vec(Meter)], ['query']),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getTransaction' : IDL.Func(
        [TransactionId],
        [IDL.Opt(Transaction)],
        ['query'],
      ),
    'purchaseToken' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : TokenResult, 'err' : IDL.Text })],
        [],
      ),
    'setAdmin' : IDL.Func([IDL.Principal], [], []),
    'validateMeter' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ValidatedMeter, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };