/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalCount' : bigint,
  'recentTransactions' : Array<Transaction>,
  'totalRevenue' : bigint,
}
export interface Meter {
  'id' : MeterId,
  'displayName' : string,
  'owner' : UserId,
  'meterNumber' : string,
  'createdAt' : Timestamp,
  'disco' : string,
}
export type MeterId = bigint;
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type Timestamp = bigint;
export interface TokenResult {
  'token' : string,
  'units' : number,
  'transactionId' : TransactionId,
}
export interface Transaction {
  'id' : TransactionId,
  'customerName' : string,
  'status' : OrderStatus,
  'token' : [] | [string],
  'paymentMethod' : string,
  'owner' : UserId,
  'meterNumber' : string,
  'createdAt' : Timestamp,
  'creditAmount' : bigint,
  'disco' : string,
}
export type TransactionId = bigint;
export type UserId = Principal;
export interface ValidatedMeter {
  'customerName' : string,
  'meterNumber' : string,
  'disco' : string,
}
export interface _SERVICE {
  'addMeter' : ActorMethod<[string, string, string], Meter>,
  'completeOrder' : ActorMethod<
    [TransactionId, string, number],
    [] | [Transaction]
  >,
  'createOrder' : ActorMethod<
    [string, string, string, bigint, string],
    Transaction
  >,
  'deleteMeter' : ActorMethod<[MeterId], boolean>,
  'failOrder' : ActorMethod<[TransactionId], [] | [Transaction]>,
  'getAdmin' : ActorMethod<[], [] | [Principal]>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getMeter' : ActorMethod<[MeterId], [] | [Meter]>,
  'getMeters' : ActorMethod<[], Array<Meter>>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getTransaction' : ActorMethod<[TransactionId], [] | [Transaction]>,
  'purchaseToken' : ActorMethod<
    [string, string, bigint, string, string],
    { 'ok' : TokenResult } |
      { 'err' : string }
  >,
  'setAdmin' : ActorMethod<[Principal], undefined>,
  'validateMeter' : ActorMethod<
    [string, string],
    { 'ok' : ValidatedMeter } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];