/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type TransactionId = bigint;
export interface TokenResult {
    token: string;
    units: number;
    transactionId: TransactionId;
}
export type Timestamp = bigint;
export interface ValidatedMeter {
    customerName: string;
    meterNumber: string;
    disco: string;
}
export interface Meter {
    id: MeterId;
    displayName: string;
    owner: UserId;
    meterNumber: string;
    createdAt: Timestamp;
    disco: string;
}
export interface AdminStats {
    totalCount: bigint;
    recentTransactions: Array<Transaction>;
    totalRevenue: bigint;
}
export type MeterId = bigint;
export interface Transaction {
    id: TransactionId;
    customerName: string;
    status: OrderStatus;
    token?: string;
    paymentMethod: string;
    owner: UserId;
    meterNumber: string;
    createdAt: Timestamp;
    creditAmount: bigint;
    disco: string;
}
export enum OrderStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export interface backendInterface {
    addMeter(meterNumber: string, displayName: string, disco: string): Promise<Meter>;
    completeOrder(txId: TransactionId, token: string, units: number): Promise<Transaction | null>;
    createOrder(meterNumber: string, disco: string, customerName: string, creditAmount: bigint, paymentMethod: string): Promise<Transaction>;
    deleteMeter(meterId: MeterId): Promise<boolean>;
    failOrder(txId: TransactionId): Promise<Transaction | null>;
    getAdmin(): Promise<Principal | null>;
    getAdminStats(): Promise<AdminStats>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getMeter(meterId: MeterId): Promise<Meter | null>;
    getMeters(): Promise<Array<Meter>>;
    getMyTransactions(): Promise<Array<Transaction>>;
    getTransaction(txId: TransactionId): Promise<Transaction | null>;
    purchaseToken(meterNumber: string, disco: string, amount: bigint, customerName: string, paymentMethod: string): Promise<{
        __kind__: "ok";
        ok: TokenResult;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setAdmin(p: Principal): Promise<void>;
    validateMeter(meterNumber: string, disco: string): Promise<{
        __kind__: "ok";
        ok: ValidatedMeter;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AdminStats as _AdminStats, Meter as _Meter, OrderStatus as _OrderStatus, Timestamp as _Timestamp, TokenResult as _TokenResult, Transaction as _Transaction, TransactionId as _TransactionId, UserId as _UserId, ValidatedMeter as _ValidatedMeter } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMeter(arg0: string, arg1: string, arg2: string): Promise<Meter> {
        if (this.processError) {
            try {
                const result = await this.actor.addMeter(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMeter(arg0, arg1, arg2);
            return result;
        }
    }
    async completeOrder(arg0: TransactionId, arg1: string, arg2: number): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.completeOrder(arg0, arg1, arg2);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeOrder(arg0, arg1, arg2);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Transaction_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Transaction_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMeter(arg0: MeterId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMeter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMeter(arg0);
            return result;
        }
    }
    async failOrder(arg0: TransactionId): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.failOrder(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.failOrder(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdmin(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdmin();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdmin();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return from_candid_AdminStats_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return from_candid_AdminStats_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMeter(arg0: MeterId): Promise<Meter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeter(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeter(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMeters(): Promise<Array<Meter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeters();
            return result;
        }
    }
    async getMyTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactions();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactions();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransaction(arg0: TransactionId): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async purchaseToken(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<{
        __kind__: "ok";
        ok: TokenResult;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseToken(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseToken(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin(arg0);
            return result;
        }
    }
    async validateMeter(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: ValidatedMeter;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.validateMeter(arg0, arg1);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateMeter(arg0, arg1);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdminStats_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminStats): AdminStats {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Meter]): Meter | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TransactionId;
    customerName: string;
    status: _OrderStatus;
    token: [] | [string];
    paymentMethod: string;
    owner: _UserId;
    meterNumber: string;
    createdAt: _Timestamp;
    creditAmount: bigint;
    disco: string;
}): {
    id: TransactionId;
    customerName: string;
    status: OrderStatus;
    token?: string;
    paymentMethod: string;
    owner: UserId;
    meterNumber: string;
    createdAt: Timestamp;
    creditAmount: bigint;
    disco: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n4(_uploadFile, _downloadFile, value.status),
        token: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.token)),
        paymentMethod: value.paymentMethod,
        owner: value.owner,
        meterNumber: value.meterNumber,
        createdAt: value.createdAt,
        creditAmount: value.creditAmount,
        disco: value.disco
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCount: bigint;
    recentTransactions: Array<_Transaction>;
    totalRevenue: bigint;
}): {
    totalCount: bigint;
    recentTransactions: Array<Transaction>;
    totalRevenue: bigint;
} {
    return {
        totalCount: value.totalCount,
        recentTransactions: from_candid_vec_n10(_uploadFile, _downloadFile, value.recentTransactions),
        totalRevenue: value.totalRevenue
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TokenResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TokenResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ValidatedMeter;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ValidatedMeter;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "failed" in value ? OrderStatus.failed : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
